name: sfdc
favicon: null
layout_spectrum: 0.338436619611457
typography_spectrum: 0.9762624118011445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#022750'
    - '#00a1e1'
    - '#ffffff'
    - '#8094a9'
    - '#b6cad4'
  brandStrength: 0.012659269385039806
  lightness: 0.3397356462664902
  saturation: 0.18537281430326402
  rhythmicContrast: 0.25
purpose: []
